name: Lint code

on:
  push:
    branches: [stage]
    paths:
      - vkpr/**/*.sh
  pull_request:
    branches: [stage]
    paths:
      - vkpr/**/*.sh

jobs:
  lint:
    name: Lint shell files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.5
        with:
          files: |
            *.sh
            **/*.sh
      - name: Lint new shell files
        if: contains(steps.changed-files.outputs.added_files, '.sh')
        run: |
          shellcheck -S warning ${{steps.changed-files.outputs.added_files}}
      - name: Lint existing shell files
        if: contains(steps.changed-files.outputs.all_changed_files, '.sh')
        run: |
          shellcheck -S warning ${{steps.changed-files.outputs.all_changed_files}}
