apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: vkpr-local
image: rancher/k3s:v1.24.4-k3s1
ports:
  - nodeFilters:
      - loadbalancer
  - nodeFilters:
      - loadbalancer
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "6000"
    volumes:
      - vkpr-registry:/var/lib/registry
  config: |
    mirrors:
      "docker.io":
        endpoint:
          - http://host.k3d.internal:6001
options:
  k3d:
    wait: true
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
